- hosts: app
  sudo: True
  vars:
    - http_port: 80
  roles:
    - nginx

  post_tasks:
    - name: Install php-fpm
      apt:
        name: php-fpm
        state: installed

    - name: delete default site file
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Upload custom default to sites-available
      template:
        src: roles/nginx/templates/app_default
        dest: /etc/nginx/sites-available/default
