- hosts: lb
  sudo: True
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - nginx

  post_tasks:
    - name: delete default site file
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Setting up loadbalancer configs
      template:
        src: roles/nginx/templates/lb_default
        dest: /etc/nginx/sites-available/default
        mode: 0644
      notify:
        - restart nginx
