- hosts: lb
  sudo: True
  vars:
    - http_port: 80
  roles:
    - nginx

  post_tasks:
    - name: Setting up loadbalancer configs
      tempalate:
        src: lb.conf
        dest: /etc/nginx/conf.d/lb.conf
        mode: 0644
      notify:
        - restart nginx
