- hosts: lb
  sudo: True
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - nginx

  post_tasks:
    - name: Setting up loadbalancer configs
      template:
        src: roles/nginx/templates/lb.conf
        dest: /etc/nginx/conf.d/lb.conf
        mode: 0644
      notify:
        - restart nginx
